picard_dir: /home/public_software_annotation/software/picard-2.18.2
threads: 8
macs2_peak_type: narrow
macs2_cutoff_type: pvalue
macs2_cutoff_value: 0.05
macs2_broad_cutoff: 0.1
normalization_method: BPM
deeptools:
  matrix_mode: reference-point
  reference_point:
    point: center
    upstream: 2000
    downstream: 2000
  scale_regions:
    region_length: 5000
    upstream: 2000
    downstream: 2000
    unscaled_5prime: 0
    unscaled_3prime: 0
  bin_size: 10
  missing_data_as_zero: true
  plot:
    color_map: RdYlBu_r
    z_min: 0
    z_max: auto
    interpolation: bilinear
  bed_source: union_peaks
  custom_bed_files: {}
  gtf_files: {}
projects:
- species: TAIR
  experiment: C-ChIRP
  rawdata_dir: workflow/resources/TAIR10/C-ChIRP/fastqfile
  index_dir: workflow/anno/Bowtie2anno_TAIR10/TAIR10
  txdb: TxDb.Athaliana.BioMart.plantsmart28
  orgdb: org.At.tair.db
  modules:
    1_download: false
    2_QC: false
    3_ChIPseq: false
    4_analyse: false
- species: TAIR
  experiment: 314Com5
  rawdata_dir: workflow/resources/TAIR10/需要合并分析的314Com5 ChIP-seq数据_20260427
  index_dir: workflow/anno/Bowtie2anno_TAIR10_arabidopsis/TAIR10
  txdb: TxDb.Athaliana.BioMart.plantsmart28
  orgdb: org.At.tair.db
  modules:
    1_download: false
    2_QC: false
    3_ChIPseq: true
    4_analyse: true
- species: TAIR
  experiment: 314OE
  rawdata_dir: workflow/resources/TAIR10/314OE CUT tag-seq 20260427/cleandata
  index_dir: workflow/anno/Bowtie2anno_TAIR10_arabidopsis/TAIR10
  txdb: TxDb.Athaliana.BioMart.plantsmart28
  orgdb: org.At.tair.db
  modules:
    1_download: false
    2_QC: false
    3_ChIPseq: false
    4_analyse: false
